#include<iostream>
#include<string>
using namespace std;
int main()
{
	/*A movie in a local theater is in great demand. To help a local charity, the theater owner
has decided to donate to the charity a portion of the total amount generated from the
movie. Write a c++ program that prompts the user to input the
1. Movie name
2. Adult ticket price
3. Child ticket price
4. The number of adult tickets sold.
5. The number of child tickets sold.
6. Percentage of the amount to be donated to the charity.
First of all, you have to Calculate the total amount generated by the total sold tickets.
Then after donating to the charity from the total amount, show the remaining amount
achieved from the movie on the Screen.*/
	string movie;
	int price;
	int cost;
	int num1;
	int num2;
	int percentage;
	int total_amount = 0;
	int total_tickets = 0;
	int final_amount = 0;
	int rem_amount = 0;
	cout << "Enter the movie name : " << endl;
	cin >> movie;
	cout << " The movie name : " << movie << endl;
	cout << "Enter the adult ticket price : " << endl;
	cin >> price;
	cout << "Enter the child ticket price : " << endl;
	cin >> cost;
	cout << "Enter the number of adult tickets sold : " << endl;
	cin >> num1;
	cout << "Enter the number of child tickets sold : " << endl;
	cin >> num2;
	cout << "Enter the percentage of the amount to be donated : " << endl;
	cin >> percentage;
	total_amount = cost + price;
	total_tickets = num1 + num2;
	final_amount = total_amount * total_tickets;
	cout << "The total amount generated by the total sold tickets is : " << final_amount << endl;
	rem_amount = final_amount - ((final_amount * percentage) / 100);
	cout << "The total amount remaining after donation of charity is : " << rem_amount << endl;
	return 0;
}